---
#
# Ansible managed
#
repository:
  description: Install digitalocean agent on your system.
  homepage: https://robertdebock.nl/
  topics: digitalocean, digitaloceanagent, doagent, ansible, molecule, tox, playbook
